### ISSUE TITLE
fix provisioning check for biganimal

### ISSUE THREAD

**Issue by mw2q** [EnterpriseDB/edb-benchmarks#57]
the status message has changed from "Cluster in healthy state" to "Healthy".  Noticed in BigAnimal CLI v1.14.0.  Need to fix existing customer wrapper scripts to bignimal's cli.

maybe check to see if using the biganimal terraform module is ready?

**Comment by mw2q** [comment]
Addressing in #58

**Comment by bryan-bar** [comment]
edb-terraform now has the biganimal provider implemented so we can create a cluster alongside our machines. Currently not VPC peered with our custom VPC regions, but can be done through the GUI or CLI, if needed. The allowed ip list can be updated as well to restrict access to the biganimal cluster.
https://github.com/EnterpriseDB/edb-terraform/pull/60

**Comment by mw2q** [comment]
Closing since #58 has been merged.
